const actionType = {
  GET_HISTORIES: 'GET_HISTORIES',
  GET_HISTORIES_PENDING: 'GET_HISTORIES_PENDING',
  GET_HISTORIES_REJECTED: 'GET_HISTORIES_REJECTED',
  GET_HISTORIES_FULFILLED: 'GET_HISTORIES_FULFILLED',

  GET_PENDING_HISTORIES: 'GET_PENDING_HISTORIES',
  GET_PENDING_HISTORIES_PENDING: 'GET_PENDING_HISTORIES_PENDING',
  GET_PENDING_HISTORIES_REJECTED: 'GET_PENDING_HISTORIES_REJECTED',
  GET_PENDING_HISTORIES_FULFILLED: 'GET_PENDING_HISTORIES_FULFILLED',
}

export default actionType;