const actionType = {
  HISTORIES: 'HISTORIES',
  HISTORIES_PENDING: 'HISTORIES_PENDING',
  HISTORIES_REJECTED: 'HISTORIES_REJECTED',
  HISTORIES_FULFILLED: 'HISTORIES_FULFILLED'
}

export default actionType;