const actionType = {
  GET_GENRES: 'GET_GENRES',
  GET_GENRES_PENDING: 'GET_GENRES_PENDING',
  GET_GENRES_REJECTED: 'GET_GENRES_REJECTED',
  GET_GENRES_FULFILLED: 'GET_GENRES_FULFILLED',

  ADD_GENRE: 'ADD_GENRE',
  ADD_GENRE_PENDING: 'ADD_GENRE_PENDING',
  ADD_GENRE_REJECTED: 'ADD_GENRE_REJECTED',
  ADD_GENRE_FULFILLED: 'ADD_GENRE_FULFILLED',

  PATCH_GENRE: 'PATCH_GENRE',
  PATCH_GENRE_PENDING: 'PATCH_GENRE_PENDING',
  PATCH_GENRE_REJECTED: 'PATCH_GENRE_REJECTED',
  PATCH_GENRE_FULFILLED: 'PATCH_GENRE_FULFILLED',

  DELETE_GENRE: 'DELETE_GENRE',
  DELETE_GENRE_PENDING: 'DELETE_GENRE_PENDING',
  DELETE_GENRE_REJECTED: 'DELETE_GENRE_REJECTED',
  DELETE_GENRE_FULFILLED: 'DELETE_GENRE_FULFILLED',

}

export default actionType;