const actionType = {
  GET_AUTHORS: 'GET_AUTHORS',
  GET_AUTHORS_PENDING: 'GET_AUTHORS_PENDING',
  GET_AUTHORS_REJECTED: 'GET_AUTHORS_REJECTED',
  GET_AUTHORS_FULFILLED: 'GET_AUTHORS_FULFILLED',

  ADD_AUTHOR: 'ADD_AUTHOR',
  ADD_AUTHOR_PENDING: 'ADD_AUTHOR_PENDING',
  ADD_AUTHOR_REJECTED: 'ADD_AUTHOR_REJECTED',
  ADD_AUTHOR_FULFILLED: 'ADD_AUTHOR_FULFILLED',

  PATCH_AUTHOR: 'PATCH_AUTHOR',
  PATCH_AUTHOR_PENDING: 'PATCH_AUTHOR_PENDING',
  PATCH_AUTHOR_REJECTED: 'PATCH_AUTHOR_REJECTED',
  PATCH_AUTHOR_FULFILLED: 'PATCH_AUTHOR_FULFILLED',

  DELETE_AUTHOR: 'DELETE_AUTHOR',
  DELETE_AUTHOR_PENDING: 'DELETE_AUTHOR_PENDING',
  DELETE_AUTHOR_REJECTED: 'DELETE_AUTHOR_REJECTED',
  DELETE_AUTHOR_FULFILLED: 'DELETE_AUTHOR_FULFILLED'
}

export default actionType;