const actionType = {
  LOGIN: 'LOGIN',
  LOGIN_PENDING: 'LOGIN_PENDING',
  LOGIN_REJECTED: 'LOGIN_REJECTED',
  LOGIN_FULFILLED: 'LOGIN_FULFILLED',

  REGISTER: 'REGISTER',
  REGISTER_PENDING: 'REGISTER_PENDING',
  REGISTER_REJECTED: 'REGISTER_REJECTED',
  REGISTER_FULFILLED: 'REGISTER_FULFILLED',

  LOGOUT: 'LOGOUT',
}

export default actionType;